// Generated by js_of_ocaml 3.2.1
(function(a){"use strict";var
ae=" : flags Open_text and Open_binary are not compatible",T="Sys_error",ad=224,ac="Invalid_argument",r=1024,z="jsError",S=57343,ab=512,aa="End_of_file",$="Failure",Q="Undefined_recursive_module",R=" : flags Open_rdonly and Open_wronly are not compatible",P="([^/]*)",_="Stack_overflow",g=128,d="",y="^",L=" : file already exists",M=2048,N=56320,O=240,f=248,Z="Not_found",K="Assert_failure",m="/",X="Sys_blocked_io",Y="fd ",J="Out_of_memory",W="Match_failure",U="Division_by_zero",V="static/",aM=0;function
v(){return aM++}function
aC(){return typeof
module!=="undefined"&&module&&module.exports?module.exports:a}function
aD(){var
c=a.console?a.console:{},d=["log","debug","info","warn","error","assert","dir","dirxml","trace","group","groupCollapsed","groupEnd","time","timeEnd"];function
e(){}for(var
b=0;b<d.length;b++)if(!c[d[b]])c[d[b]]=e;return c}function
aj(a){if(a.length<24){for(var
b=0;b<a.length;b++)if(a.charCodeAt(b)>127)return false;return true}else
return!/[^\x00-\x7f]/.test(a)}function
aU(f){for(var
h=d,b=h,a,j,c=0,i=f.length;c<i;c++){a=f.charCodeAt(c);if(a<g){for(var
e=c+1;e<i&&(a=f.charCodeAt(e))<g;e++);if(e-c>ab){b.substr(0,1);h+=b;b=d;h+=f.slice(c,e)}else
b+=f.slice(c,e);if(e==i)break;c=e}if(a<M){b+=String.fromCharCode(192|a>>6);b+=String.fromCharCode(g|a&63)}else
if(a<55296||a>=S)b+=String.fromCharCode(ad|a>>12,g|a>>6&63,g|a&63);else
if(a>=56319||c+1==i||(j=f.charCodeAt(c+1))<N||j>S)b+="\xef\xbf\xbd";else{c++;a=(a<<10)+j-56613888;b+=String.fromCharCode(O|a>>18,g|a>>12&63,g|a>>6&63,g|a&63)}if(b.length>r){b.substr(0,1);h+=b;b=d}}return h+b}function
aQ(b,a){if(a.repeat)return a.repeat(b);var
c=d,e=0;if(b==0)return c;for(;;){if(b&1)c+=a;b>>=1;if(b==0)return c;a+=a;e++;if(e==9)a.slice(0,1)}}function
aZ(d,e,c){var
b=new
Array(c);for(var
a=0;a<c;a++)b[a]=d[e+a];return b}function
D(b,c,a){var
e=String.fromCharCode;if(c==0&&a<=4096&&a==b.length)return e.apply(null,b);var
f=d;for(;0<a;c+=r,a-=r)f+=e.apply(null,aZ(b,c,Math.min(a,r)));return f}function
ah(a){if(a.t==2)a.c+=aQ(a.l-a.c.length,"\0");else
a.c=D(a.c,0,a.c.length);a.t=0}function
aT(f){for(var
l=d,c=d,i,h,j,a,b=0,k=f.length;b<k;b++){h=f.charCodeAt(b);if(h<g){for(var
e=b+1;e<k&&(h=f.charCodeAt(e))<g;e++);if(e-b>ab){c.substr(0,1);l+=c;c=d;l+=f.slice(b,e)}else
c+=f.slice(b,e);if(e==k)break;b=e}a=1;if(++b<k&&((j=f.charCodeAt(b))&-64)==g){i=j+(h<<6);if(h<ad){a=i-12416;if(a<g)a=1}else{a=2;if(++b<k&&((j=f.charCodeAt(b))&-64)==g){i=j+(i<<6);if(h<O){a=i-925824;if(a<M||a>=55295&&a<57344)a=2}else{a=3;if(++b<k&&((j=f.charCodeAt(b))&-64)==g&&h<245){a=j-63447168+(i<<6);if(a<65536||a>1114111)a=3}}}}}if(a<4){b-=a;c+="\ufffd"}else
if(a>65535)c+=String.fromCharCode(55232+(a>>10),N+(a&1023));else
c+=String.fromCharCode(a);if(c.length>r){c.substr(0,1);l+=c;c=d}}return l+c}function
aS(a){switch(a.t){case
9:return a.c;default:ah(a);case
0:if(aj(a.c)){a.t=9;return a.c}a.t=8;case
8:return aT(a.c)}}function
n(c,a,b){this.t=c;this.c=a;this.l=b}n.prototype.toString=function(){return aS(this)};function
C(a){var
b=9;if(!aj(a))b=8,a=aU(a);return new
n(b,a,a.length)}function
aO(b,a){throw[0,b,a]}function
c(a){return new
n(0,a,a.length)}function
an(b,a){aO(b,c(a))}var
b=[0];function
j(a){an(b.Sys_error,a)}var
o=new
Array();function
aH(e){var
a=o[e];if(!a.opened)j("Cannot flush a closed channel");if(!a.buffer||a.buffer==d)return 0;if(a.fd&&b.fds[a.fd]&&b.fds[a.fd].output){var
c=b.fds[a.fd].output;switch(c.length){case
2:c(e,a.buffer);break;default:c(a.buffer)}}a.buffer=d;return 0}if(a.process&&a.process.cwd)var
s=a.process.cwd().replace(/\\/g,m);else
var
s="/static";if(s.slice(-1)!==m)s+=m;function
aF(a){a=a
instanceof
n?a.toString():a;if(a.charCodeAt(0)!=47)a=s+a;var
e=a.split(m),b=[];for(var
c=0;c<e.length;c++)switch(e[c]){case"..":if(b.length>1)b.pop();break;case".":break;case"":if(b.length==0)b.push(d);break;default:b.push(e[c]);break}b.orig=a;return b}function
aN(a){a=a
instanceof
n?a.toString():a;j(a+": No such file or directory")}function
aR(a){return new
n(4,a,a.length)}function
ai(a){an(b.Invalid_argument,a)}function
aq(){ai("index out of bounds")}function
aA(a,b){switch(a.t&6){default:if(b>=a.c.length)return 0;case
0:return a.c.charCodeAt(b);case
4:return a.c[b]}}function
ay(b,a){if(a>>>0>=b.l)aq();return aA(b,a)}function
p(a){if(a<0)ai("Bytes.create");return new
n(a?2:9,d,a)}function
aG(a){return a.l}function
B(c){if(a.Uint8Array)var
d=new(a.Uint8Array)(c.l);else
var
d=new
Array(c.l);var
f=c.c,e=f.length,b=0;for(;b<e;b++)d[b]=f.charCodeAt(b);for(e=c.l;b<e;b++)d[b]=0;c.c=d;c.t=4;return d}function
u(d,e,b,f,c){if(c==0)return 0;if(f==0&&(c>=b.l||b.t==2&&c>=b.c.length)){b.c=d.t==4?D(d.c,e,c):e==0&&d.c.length==c?d.c:d.c.substr(e,c);b.t=b.c.length==b.l?0:2}else
if(b.t==2&&f==b.c.length){b.c+=d.t==4?D(d.c,e,c):e==0&&d.c.length==c?d.c:d.c.substr(e,c);b.t=b.c.length==b.l?0:2}else{if(b.t!=4)B(b);var
g=d.c,h=b.c;if(d.t==4)if(f<=e)for(var
a=0;a<c;a++)h[f+a]=g[e+a];else
for(var
a=c-1;a>=0;a--)h[f+a]=g[e+a];else{var
i=Math.min(c,g.length-e);for(var
a=0;a<i;a++)h[f+a]=g.charCodeAt(e+a);for(;a<c;a++)h[f+a]=0}}return 0}function
af(){}function
e(a){this.data=a}e.prototype=new
af();e.prototype.truncate=function(a){var
b=this.data;this.data=p(a|0);u(b,0,this.data,0,a)};e.prototype.length=function(){return aG(this.data)};e.prototype.write=function(b,d,g,a){var
c=this.length();if(b+a>=c){var
e=p(b+a),f=this.data;this.data=e;u(f,0,this.data,0,c)}u(d,g,this.data,b,a);return 0};e.prototype.read=function(c,a,d,b){var
e=this.length();u(this.data,c,a,d,b);return 0};e.prototype.read_one=function(a){return ay(this.data,a)};e.prototype.close=function(){};e.prototype.constructor=e;function
h(b,a){this.content={};this.root=b;this.lookupFun=a}h.prototype.nm=function(a){return this.root+a};h.prototype.lookup=function(a){if(!this.content[a]&&this.lookupFun){var
b=this.lookupFun(c(this.root),c(a));if(b!=0)this.content[a]=new
e(b[1])}};h.prototype.exists=function(a){if(a==d)return 1;var
c=a+m,e=new
RegExp(y+c);for(var
b
in
this.content)if(b.match(e))return 1;this.lookup(a);return this.content[a]?1:0};h.prototype.readdir=function(c){var
g=c==d?d:c+m,h=new
RegExp(y+g+P),e={},b=[];for(var
f
in
this.content){var
a=f.match(h);if(a&&!e[a[1]]){e[a[1]]=true;b.push(a[1])}}return b};h.prototype.is_dir=function(a){var
e=a==d?d:a+m,f=new
RegExp(y+e+P),g=[];for(var
c
in
this.content){var
b=c.match(f);if(b)return 1}return 0};h.prototype.unlink=function(a){var
b=this.content[a]?true:false;delete
this.content[a];return b};h.prototype.open=function(a,b){if(b.rdonly&&b.wronly)j(this.nm(a)+R);if(b.text&&b.binary)j(this.nm(a)+ae);this.lookup(a);if(this.content[a]){if(this.is_dir(a))j(this.nm(a)+" : is a directory");if(b.create&&b.excl)j(this.nm(a)+L);var
c=this.content[a];if(b.truncate)c.truncate();return c}else
if(b.create){this.content[a]=new
e(p(0));return this.content[a]}else
aN(this.nm(a))};h.prototype.register=function(b,a){if(this.content[b])j(this.nm(b)+L);if(a
instanceof
n)this.content[b]=new
e(a);else
if(a
instanceof
Array)this.content[b]=new
e(aR(a));else
if(a.toString){var
d=c(a.toString());this.content[b]=new
e(d)}};h.prototype.constructor=h;function
ag(a){if(a.t!=4)B(a);return a.c}function
aB(a,c,b){b&=255;if(a.t!=4){if(c==a.c.length){a.c+=String.fromCharCode(b);if(c+1==a.l)a.t=0;return 0}B(a)}a.c[c]=b;return 0}function
az(b,a,c){if(a>>>0>=b.l)aq();return aB(b,a,c)}var
A=a.Buffer;function
l(a){this.fs=require("fs");this.fd=a}l.prototype=new
af();l.prototype.truncate=function(a){this.fs.ftruncateSync(this.fd,a|0)};l.prototype.length=function(){return this.fs.fstatSync(this.fd).size};l.prototype.write=function(g,c,d,f){var
b=ag(c);if(!(b
instanceof
a.Uint8Array))b=new(a.Uint8Array)(b);var
e=new
A(b);this.fs.writeSync(this.fd,e,d,f,g);return 0};l.prototype.read=function(h,e,d,g){var
b=ag(e);if(!(b
instanceof
a.Uint8Array))b=new(a.Uint8Array)(b);var
f=new
A(b);this.fs.readSync(this.fd,f,d,g,h);for(var
c=0;c<g;c++)az(e,d+c,f[d+c]);return 0};l.prototype.read_one=function(d){var
c=new(a.Uint8Array)(1),b=new
A(c);this.fs.readSync(this.fd,b,0,1,d);return b[0]};l.prototype.close=function(){this.fs.closeSync(this.fd)};l.prototype.constructor=l;function
k(a){this.fs=require("fs");this.root=a}k.prototype.nm=function(a){return this.root+a};k.prototype.exists=function(a){return this.fs.existsSync(this.nm(a))?1:0};k.prototype.readdir=function(a){return this.fs.readdirSync(this.nm(a))};k.prototype.is_dir=function(a){return this.fs.statSync(this.nm(a)).isDirectory()?1:0};k.prototype.unlink=function(a){var
b=this.fs.existsSync(this.nm(a))?1:0;this.fs.unlinkSync(this.nm(a));return b};k.prototype.open=function(f,c){var
a=require("constants"),b=0;for(var
e
in
c)switch(e){case"rdonly":b|=a.O_RDONLY;break;case"wronly":b|=a.O_WRONLY;break;case"append":b|=a.O_WRONLY|a.O_APPEND;break;case"create":b|=a.O_CREAT;break;case"truncate":b|=a.O_TRUNC;break;case"excl":b|=a.O_EXCL;break;case"binary":b|=a.O_BINARY;break;case"text":b|=a.O_TEXT;break;case"nonblock":b|=a.O_NONBLOCK;break}var
d=this.fs.openSync(this.nm(f),b);return new
l(d)};k.prototype.rename=function(b,a){this.fs.renameSync(this.nm(b),this.nm(a))};k.prototype.constructor=k;var
q=s.match(/[^\/]*\//)[0];function
aW(){return typeof
a.process!=="undefined"&&typeof
a.process.versions!=="undefined"&&typeof
a.process.versions.node!=="undefined"}var
t=[];if(aW())t.push({path:q,device:new
k(q)});else
t.push({path:q,device:new
h(q)});t.push({path:q+V,device:new
h(q+V)});function
a0(b){var
f=aF(b),b=f.join(m),e=b+m,c;for(var
d=0;d<t.length;d++){var
a=t[d];if(e.search(a.path)==0&&(!c||c.path.length<a.path.length))c={path:a.path,device:a.device,rest:b.substring(a.path.length,b.length)}}return c}function
aK(a){return a.l}function
ap(e,f){var
a=o[e],d=c(f),b=aK(d);a.file.write(a.offset,d,0,b);a.offset+=b;return 0}function
aX(b){var
c=a;if(c.process&&c.process.stdout&&c.process.stdout.write)c.process.stderr.write(b);else{if(b.charCodeAt(b.length-1)==10)b=b.substr(0,b.length-1);var
d=c.console;d&&d.error&&d.error(b)}}function
aY(b){var
c=a;if(c.process&&c.process.stdout&&c.process.stdout.write)c.process.stdout.write(b);else{if(b.charCodeAt(b.length-1)==10)b=b.substr(0,b.length-1);var
d=c.console;d&&d.log&&d.log(b)}}function
w(d,f,e,a){if(b.fds===undefined)b.fds=new
Array();a=a?a:{};var
c={};c.file=e;c.offset=a.append?e.length():0;c.flags=a;c.output=f;b.fds[d]=c;if(!b.fd_last_idx||d>b.fd_last_idx)b.fd_last_idx=d;return d}function
a1(d,c,h){var
a={};while(c){switch(c[1]){case
0:a.rdonly=1;break;case
1:a.wronly=1;break;case
2:a.append=1;break;case
3:a.create=1;break;case
4:a.truncate=1;break;case
5:a.excl=1;break;case
6:a.binary=1;break;case
7:a.text=1;break;case
8:a.nonblock=1;break}c=c[2]}if(a.rdonly&&a.wronly)j(d.toString()+R);if(a.text&&a.binary)j(d.toString()+ae);var
e=a0(d),f=e.device.open(e.rest,a),g=b.fd_last_idx?b.fd_last_idx:0;return w(g+1,ap,f,a)}w(0,ap,new
e(p(0)));w(1,aY,new
e(p(0)));w(2,aX,new
e(p(0)));function
aI(d){var
c=b.fds[d];if(c.flags.wronly)j(Y+d+" is writeonly");var
a={file:c.file,offset:c.offset,fd:d,opened:true,out:false,refill:null};o[a.fd]=a;return a.fd}function
ak(e){var
c=b.fds[e];if(c.flags.rdonly)j(Y+e+" is readonly");var
a={file:c.file,offset:c.offset,fd:e,opened:true,out:true,buffer:d};o[a.fd]=a;return a.fd}function
aJ(){var
b=0;for(var
a=0;a<o.length;a++)if(o[a]&&o[a].opened&&o[a].out)b=[0,o[a].fd,b];return b}function
aL(a){return a
instanceof
Array?a[0]:a
instanceof
n?252:1e3}function
i(d,c,a){b[d+1]=c;if(a)b[a]=c}var
am={};function
aE(a){if((a.t&6)!=0)ah(a);return a.c}function
aP(a,b){am[aE(a)]=b;return 0}function
ao(a){return a}function
al(a){return am[a]}function
aV(c){if(c
instanceof
Array)return c;if(a.RangeError&&c
instanceof
a.RangeError&&c.message&&c.message.match(/maximum call stack/i))return ao(b.Stack_overflow);if(a.InternalError&&c
instanceof
a.InternalError&&c.message&&c.message.match(/too much recursion/i))return ao(b.Stack_overflow);if(c
instanceof
a.Error&&al(z))return[0,al(z),c];return[0,b.Failure,C(String(c))]}var
E=[f,c(T),-2];i(11,[f,c(Q),-12],Q);i(10,[f,c(K),-11],K);i(9,[f,c(X),-10],X);i(8,[f,c(_),-9],_);i(7,[f,c(W),-8],W);i(6,[f,c(Z),-7],Z);i(5,[f,c(U),-6],U);i(4,[f,c(aa),-5],aa);i(3,[f,c(ac),-4],ac);i(2,[f,c($),-3],$);i(1,E,T);i(0,[f,c(J),-1],J);v(0);aI(0);ak(1);ak(2);v(0);v(0);var
F=[0,0],au=c("Js.Error"),ax=c("foo");function
G(a){F[1]=[0,a,F[1]];return 0}var
at=a.Array,H=[f,au,v(0)],x=[0,H,{}],as=aL(x)===f?x:x[1];aP(c(z),as);(function(a){throw a});G(function(a){return a[1]===H?[0,C(a[2].toString())]:0});G(function(a){return a
instanceof
at?0:[0,C(a.toString())]});var
av=aD(0);function
I(a){return av.log(a)}function
aw(a){return I(a)}aC(0).__useResumable=aw;I(ax);function
ar(b){var
a=b;for(;;){if(a){var
c=a[2],d=a[1];try{aH(d)}catch(a){a=aV(a);if(a[1]!==E)throw a}var
a=c;continue}return 0}}ar(aJ(0));return}(function(){return this}()));
